export {
  GET_POKEMON_LIST,
  GET_POKEMON_LIST_BY_ID,
  GET_POKEMON_LIST_BY_NAME,
  GET_POKEMON_DETAIL,
  GET_POKEMON_BY_ID,
  GET_POKEMON_BY_NAME,
  GET_POKEMON_TYPES,
  GET_POKEMON_BY_TYPE
} from './pokemon.queries'

